run:
  timeout: 5m
  tests: false


linters-settings:
  cyclop:
    max-complexity: 30
    package-average: 10.0

  exhaustive:
    check:
      - switch
      - map

  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 20

  gocritic:
    settings:
      captLocal:
        paramsOnly: false
      underef:
        skipRecvDeref: false

  nakedret:
    max-func-lines: 0

  nolintlint:
    allow-no-explanation: [ funlen, gocognit, lll ]
    require-explanation: true
    require-specific: true

  tenv:
    all: true

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/d6o/find-flight-path)
      - blank
      - dot

    skip-generated: true
    custom-order: true


linters:
  enable:
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - lll
    - loggercheck
    - makezero
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - tenv
    - testableexamples
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - gofumpt
    - decorder
    - gci
    - ginkgolinter
    - godox
    - goheader
    - interfacebloat
    - prealloc
    - containedctx
    - importas
    - misspell

issues:
  max-same-issues: 50
  fix: true
