version: '3'
services:

  ports:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      STORAGE_PROVIDER: "redis"
      REDIS_ADDRESS: "redis:6379"
      API_PORT: "8080"
    ports:
      - '8080:8080'
    tty: true
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - '6379:6379'
