// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: resources/proto/port.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PortKey string `protobuf:"bytes,1,opt,name=port_key,json=portKey,proto3" json:"port_key,omitempty"`
}

func (x *GetPortRequest) Reset() {
	*x = GetPortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_port_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortRequest) ProtoMessage() {}

func (x *GetPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_port_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortRequest.ProtoReflect.Descriptor instead.
func (*GetPortRequest) Descriptor() ([]byte, []int) {
	return file_resources_proto_port_proto_rawDescGZIP(), []int{0}
}

func (x *GetPortRequest) GetPortKey() string {
	if x != nil {
		return x.PortKey
	}
	return ""
}

type GetPortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	City     string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country  string   `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Alias    []string `protobuf:"bytes,4,rep,name=alias,proto3" json:"alias,omitempty"`
	Regions  []string `protobuf:"bytes,5,rep,name=regions,proto3" json:"regions,omitempty"`
	Lat      float64  `protobuf:"fixed64,6,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon      float64  `protobuf:"fixed64,7,opt,name=lon,proto3" json:"lon,omitempty"`
	Province string   `protobuf:"bytes,8,opt,name=province,proto3" json:"province,omitempty"`
	Timezone string   `protobuf:"bytes,9,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Unlocs   []string `protobuf:"bytes,10,rep,name=unlocs,proto3" json:"unlocs,omitempty"`
	Code     string   `protobuf:"bytes,11,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetPortResponse) Reset() {
	*x = GetPortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_port_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortResponse) ProtoMessage() {}

func (x *GetPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_port_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortResponse.ProtoReflect.Descriptor instead.
func (*GetPortResponse) Descriptor() ([]byte, []int) {
	return file_resources_proto_port_proto_rawDescGZIP(), []int{1}
}

func (x *GetPortResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPortResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetPortResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetPortResponse) GetAlias() []string {
	if x != nil {
		return x.Alias
	}
	return nil
}

func (x *GetPortResponse) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *GetPortResponse) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GetPortResponse) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GetPortResponse) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *GetPortResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *GetPortResponse) GetUnlocs() []string {
	if x != nil {
		return x.Unlocs
	}
	return nil
}

func (x *GetPortResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_resources_proto_port_proto protoreflect.FileDescriptor

var file_resources_proto_port_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x22, 0x2b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x22,
	0x8b, 0x02, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x45, 0x0a,
	0x0b, 0x50, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x70, 0x6f, 0x72, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_resources_proto_port_proto_rawDescOnce sync.Once
	file_resources_proto_port_proto_rawDescData = file_resources_proto_port_proto_rawDesc
)

func file_resources_proto_port_proto_rawDescGZIP() []byte {
	file_resources_proto_port_proto_rawDescOnce.Do(func() {
		file_resources_proto_port_proto_rawDescData = protoimpl.X.CompressGZIP(file_resources_proto_port_proto_rawDescData)
	})
	return file_resources_proto_port_proto_rawDescData
}

var file_resources_proto_port_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resources_proto_port_proto_goTypes = []interface{}{
	(*GetPortRequest)(nil),  // 0: port.GetPortRequest
	(*GetPortResponse)(nil), // 1: port.GetPortResponse
}
var file_resources_proto_port_proto_depIdxs = []int32{
	0, // 0: port.PortService.GetPort:input_type -> port.GetPortRequest
	1, // 1: port.PortService.GetPort:output_type -> port.GetPortResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resources_proto_port_proto_init() }
func file_resources_proto_port_proto_init() {
	if File_resources_proto_port_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resources_proto_port_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_port_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resources_proto_port_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resources_proto_port_proto_goTypes,
		DependencyIndexes: file_resources_proto_port_proto_depIdxs,
		MessageInfos:      file_resources_proto_port_proto_msgTypes,
	}.Build()
	File_resources_proto_port_proto = out.File
	file_resources_proto_port_proto_rawDesc = nil
	file_resources_proto_port_proto_goTypes = nil
	file_resources_proto_port_proto_depIdxs = nil
}
